Configs:
  - Name: 0_dynamic_0_LP
    AverageMarketPriceInEURPerMWH: 10
    CapacityBasedNetworkChargesInEURPerMW: 0
    DynamicTariffComponents: []

  - Name: 20_dynamic_0_LP
    AverageMarketPriceInEURPerMWH: 10
    CapacityBasedNetworkChargesInEURPerMW: 0
    DynamicTariffComponents:
      - ComponentName: POWER_PRICE
        Multiplier: 0.2
        LowerBound: -500.0
        UpperBound: 3000.0
      - ComponentName: OTHER_COMPONENTS
        Multiplier: 0.2
        LowerBound: -500.0
        UpperBound: 3000.0

  - Name: 0_dynamic_20_LP
    AverageMarketPriceInEURPerMWH: 8
    CapacityBasedNetworkChargesInEURPerMW: 1000
    DynamicTariffComponents: []