# Workflow control
config_workflow:
  template_folder: "./template/"
  input_folder: "./inputs/"
  data_sub_folder: "data"
  scenario_sub_folder: "scenarios"
  tariff_config:
    mode: "from_workflow"  # "from_file"
    config_file: "tariff_configuration_ALL"  # "tariff_configuration"
    energy:
      step_size: 100
      min_share: 0
      max_share: 100
    capacity:
      step_size: 100
      min_share: 0
      max_share: 100
  output_folder: "./results/"
  data_output: "data_out/"
  plots_output: "plots_out/"
  demand_response_scenarios:
#    "5": "scenario_w_dr_5"
    "50": "scenario_w_dr_50"
#    "95": "scenario_w_dr_95"
  load_shifting_focus_cluster: "ind_cluster_shift_only"
  investment_year: 2020
  interest_rate: 0.1
  inflation_rate: 1.02
  network_tariff_growth_rate: 1.07  # analytical estimate
  prepare_tariff_config: True
  simulation:
    StartTime: 2026-12-31_23:58:00  # 2026-12-31_23:58:00
    StopTime: 2027-12-31_23:58:00  # 2027-12-31_23:58:00
    artificial_shortage_capacity_in_MW: 100000
    minimum_value_of_lost_load: 300
  amiris_analyses:
    skip_simulation: False
    start_web_service: True
    make_scenario: True
    run_amiris: True
    convert_results: True
    process_results: True
    use_baseline_prices_for_comparison: True
    aggregate_results: True
  annuity_mode: "single_year"  # "single_year", "multiple_years"
  lifetime: 15  # only for annuity_mode "single_year"
  activate_flh_check: False
  write_results: True
  evaluate_cross_scenarios: True
  make_plots: True
  baseline_load_file: "baseline_load_profile"

# Plotting control
config_plotting:
  very_small_size: 10
  small_size: 12
  medium_size: 14
  bigger_size: 15
  width:
    bar: 10
    heatmap: 8
  height:
    bar: 6
    heatmap: 6
  drop_list: []
  language: "English"  # "German", "English"
  format_axis: True
  division:
    "Annuity": 1e6
    "CapacityPaymentAfterShifting": 1e6
    "CapacityPaymentBeforeShifting": 1e6
    "CapacityPaymentChange": 1e6
    "EnergyPaymentAfterShifting": 1e6
    "EnergyPaymentBeforeShifting": 1e6
    "EnergyPaymentChange": 1e6
    "InvestmentExpenses": 1e6
    "NetPresentValue": 1e6
    "NetPresentValuePerCapacity": 1e3
    "Net Savings": 1e6
    "TotalPaymentAfterShifting": 1e6
    "TotalPaymentBeforeShifting": 1e6
    "TotalPaymentLoadChange": 1e6
    "TotalShiftingCosts": 1e6
  y_limits:
    "NetPresentValuePerCapacity":
      "limits": [-20000, 20000]
      "log_y": False
      "cbar_limit": 0.2
  rename_dict:
    columns: {}
    rows: {}
    derive_column_names: True
    index_name:
      "English": "capacity tariff share in %"
      "German": "Leistungspreisanteil in %"
    columns_name:
      "English": "dynamic tariff share in %"
      "German": "dynamischer Anteil des Arbeitspreises in %"
    parameters:
      "English":
        "Annuity": "Annuity in Mio. EUR"
        "CapacityPaymentAfterShifting": "Capacity Payment After Shifting in Mio. EUR"
        "CapacityPaymentBeforeShifting": "Capacity Payment Before Shifting in Mio. EUR"
        "CapacityPaymentChange": "Change in Capacity Payment in Mio. EUR"
        "EnergyPaymentAfterShifting": "Energy Payment After Shifting in Mio. EUR"
        "EnergyPaymentBeforeShifting": "Energy Payment Before Shifting in Mio. EUR"
        "EnergyPaymentChange": "Change in Energy Payment in Mio. EUR"
        "InvestmentExpenses": "Investment Expenses in Mio. EUR"
        "NetPresentValue": "Net Present Value in Mio. EUR"
        "NetPresentValuePerCapacity": "Net Present Value per Capacity in thousand EUR per MW"
        "NetSavings": "Net Savings in Mio. EUR"
        "NoOfFullShiftCycles": "Number of full shift cycles in 1"
        "PeakLoadAfterShifting": "Peak Load After Shifting in MW"
        "PeakLoadBeforeShifting": "Peak Load Before Shifting in MW"
        "PeakLoadChange": "Change in Peak Load in MW"
        "TotalPaymentAfterShifting": "Total Payment After Shifting in Mio. EUR"
        "TotalPaymentBeforeShifting": "Total Payment Before Shifting in Mio. EUR"
        "TotalPaymentChange": "Change in Total Payment in Mio. EUR"
        "TotalShiftingCosts": "Total Variable Shifting Costs in Mio. EUR"
      "German":
        "Annuity": "Annuität in Mio. EUR"
        "CapacityPaymentAfterShifting": "Leistungspreiszahlungen nach Lastverschiebung in Mio. EUR"
        "CapacityPaymentBeforeShifting": "Leistungspreiszahlungen vor Lastverschiebung in Mio. EUR"
        "CapacityPaymentChange": "Änderung der Leistungspreiszahlungen in Mio. EUR"
        "EnergyPaymentAfterShifting": "Arbeitspreiszahlungen nach Lastverschiebung in Mio. EUR"
        "EnergyPaymentBeforeShifting": "Arbeitspreiszahlungen vor Lastverschiebung in Mio. EUR"
        "EnergyPaymentChange": "Änderung der Arbeitspreiszahlungen in Mio. EUR"
        "InvestmentExpenses": "Investitionsausgaben in Mio. EUR"
        "NetPresentValue": "Kapitalwert in Mio. EUR"
        "NetPresentValuePerCapacity": "Kapitalwert pro flexibler Leistung in TEUR pro MW"
        "NetSavings": "Nettoeinsparungen in Mio. EUR"
        "NoOfFullShiftCycles": "Anzahl der Vollverschiebezyklen in 1"
        "PeakLoadAfterShifting": "Spitzenlast nach Lastverschiebung in MW"
        "PeakLoadBeforeShifting": "Spitzenlast vor Lastverschiebung in MW"
        "PeakLoadChange": "Änderung der Spitzenlast in MW"
        "TotalPaymentAfterShifting": "Gesamte Zahlungen nach Lastverschiebung in Mio. EUR"
        "TotalPaymentBeforeShifting": "Gesamte Zahlungen vor Lastverschiebung in Mio. EUR"
        "TotalPaymentChange": "Änderung der gesamten Zahlungen in Mio. EUR"
        "TotalShiftingCosts": "Gesamte variable Lastverschiebekosten in Mio. EUR"
  x_label: None
  annotate: True
  save_plot: True
  show_plot: False

# fameio make control
config_make:
  Options.LOG_LEVEL: "error"
  Options.LOG_FILE: None
# Config.NUM_PROCESSES: 1

# AMIRIS run properties
run_properties:
  exe: "amiris/amiris-core_1.2.16-jar-with-dependencies.jar -Xmx16000M"
  logging: "-Dlog4j.configuration=file:amiris/log4j.properties"
  main: "de.dlr.gitlab.fame.setup.FameRunner"
  setup: "amiris/fameSetup.yaml"

# fameio convert control
config_convert:
  Options.LOG_LEVEL: "warn"
  Options.LOG_FILE: None
  Options.AGENT_LIST: ["DemandTrader", "EnergyExchangeMulti", "LoadShiftingTrader", "VariableRenewableOperator"]  # None
  Options.OUTPUT: None  # set in workflow
  Options.SINGLE_AGENT_EXPORT: False
  Options.MEMORY_SAVING: False
  Options.RESOLVE_COMPLEX_FIELD: ResolveOptions.IGNORE