# Workflow control
config_workflow:
  template_folder: "./template/"
  input_folder: "./inputs/"
  data_sub_folder: "data"
  scenario_sub_folder: "scenarios"
  tariff_config_file: "tariff_configuration"
  output_folder: "./results/"
  data_output: "data_out/"
  plots_output: "plots_out/"
  demand_response_scenarios:
    "5": "scenario_w_dr_5"
    "50": "scenario_w_dr_50"
    "95": "scenario_w_dr_95"
  load_shifting_focus_cluster: "ind_cluster_shift_only"
  load_shedding_clusters: [
    "ind_cluster_shed_only",
    "ind_cluster_shift_shed",
    "hoho_cluster_shift_shed",
  ]
  interest_rate: 0.05
  prepare_tariff_config: True
  artificial_shortage_capacity_in_MW: 100000
  amiris_analyses:
    start_web_service: True
    make_scenario: True
    run_amiris: True
    convert_results: True
    process_results: True
    use_baseline_prices_for_comparison: True
    aggregate_results: True
  annuity_mode: "single_year"  # "single_year", "multiple_years"
  lifetime: 15  # only for annuity_mode "single_year"
  write_results: True
  evaluate_cross_scenarios: True
  make_plots: True
  baseline_load_file: "baseline_load_profile"

# Plotting control
config_plotting:
  small_size: 12
  medium_size: 14
  bigger_size: 15
  width: 10
  height: 7
  drop_list: []
  rename_dict:
    columns: {}
    rows: {}
    parameters: {}
  x_label: None
  save_plot: True
  show_plot: False

# fameio make control
config_make:
  Options.LOG_LEVEL: "error"
  Options.LOG_FILE: None
# Config.NUM_PROCESSES: 1

# AMIRIS run properties
run_properties:
  exe: "amiris/amiris-core_1.2.9-jar-with-dependencies.jar -Xmx16000M"
  logging: "-Dlog4j.configuration=file:amiris/log4j.properties"
  main: "de.dlr.gitlab.fame.setup.FameRunner"
  setup: "amiris/fameSetup.yaml"

# fameio convert control
config_convert:
  Options.LOG_LEVEL: "warn"
  Options.LOG_FILE: None
  Options.AGENT_LIST: None
  Options.OUTPUT: None  # set in workflow
  Options.SINGLE_AGENT_EXPORT: False
  Options.MEMORY_SAVING: False
  Options.RESOLVE_COMPLEX_FIELD: ResolveOptions.IGNORE